apiVersion: v1
kind: Service
metadata:
  name: chris-svc
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
  {{- if lower .Values.sename }}
    app: {{lower .Values.name}}-{{lower .Values.sename}}
  {{- else }}
    app: {{lower .Values.name}}
 {{- end }}
